export const ActionType = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT_REQUEST: "SELECTED_PRODUCT_REQUEST",
  SELECTED_PRODUCT_SUCCESS: "SELECTED_PRODUCT_SUCCESS",
  SELECTED_PRODUCT_FAILED: "SELECTED_PRODUCT_FAILED",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
